name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
  - title: '📖 Docs'
    labels:
      - 'docs'
  - title: '🧪 Tests'
    labels:
      - 'test'
  - title: '🧹 Chores'
    labels:
      - 'chore'
  - title: '🤖 CI/CD'
    labels:
      - 'ci'
  - title: '⛓️ Dependencies'
    labels:
      - 'deps'
  - title: '🔖 Other changes'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'chore'
    branch:
      - '/chore.+/'
  - label: 'bug'
    branch:
      - '/fix.+/'
      - '/bugfix.+/'
  - label: 'enhancement'
    branch:
      - '/feature.+/'
      - '/feat.+/'
      - '/enhancement.+/'
  - label: 'ci'
    branch:
      - '/ci.+/'
      - '/.*\(ci\): .*/'
  - label: 'deps'
    branch:
      - '/deps.+/'
  - label: 'test'
    branch:
      - '/test.+/'
  - label: 'docs'
    branch:
      - '/docs.+/'