---

- name: configure | write encryption key to file
  copy:
    content: "{{ rstudio_encryption_key | trim }}"
    dest: "{{ rstudio_package_manager_encryption_key_location }}"
    owner: rstudio-pm
    group: rstudio-pm
    mode: 0600
  when: rstudio_encryption_key is defined
  tags:
    - rstudio-package-manager-encryption-key

- name: configure | update (server) configuration file
  template:
    src: etc/rstudio-pm/rstudio-pm.gcfg.j2
    dest: /etc/rstudio-pm/rstudio-pm.gcfg
    owner: root
    group: root
    mode: 0644
  notify: restart rstudio-package-manager
  tags:
    - rstudio-package-manager-configure-server

- name: configure | update (systemd) configuration file
  template:
    src: etc/systemd/system/rstudio-pm.service.d/user.conf
    dest: /etc/systemd/system/rstudio-pm.service.d/user.conf
    owner: root
    group: root
    mode: 0644
  register: rstudio_package_manager_register_daemon_user
  notify: restart rstudio-package-manager
  tags:
    - rstudio-package-manager-configure-server

- name: reload systemd daemon
  systemd:
    daemon_reload: true
  when: rstudio_package_manager_register_daemon_user is changed
  tags:
    - skip_ansible_lint

- name: restart server now
  meta: "flush_handlers"

- name: Set cap_net_bind_service+ep on /opt/rstudio-pm/bin/rstudio-pm
  community.general.capabilities:
    path: /opt/rstudio-pm/bin/rstudio-pm
    capability: cap_net_bind_service+ep
    state: present
  tags:
    - rstudio-package-manager-set-caps

- name: configure | activate server license
  shell: |
    /opt/rstudio-pm/bin/license-manager activate {{ rstudio_package_manager_license }}
  notify: restart rstudio-package-manager
  when: rstudio_package_manager_license|d()
  register: license_output
  tags:
    - rstudio-package-manager-configure-license
