# tasks file
---
- name: Include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - rstudio-package-manager
    - rstudio-package-manager-include-variables

- name: Include install
  ansible.builtin.include_tasks: install.yml
  tags:
    - configuration
    - rstudio-package-manager
    - rstudio-package-manager-install

- name: Include configure
  ansible.builtin.include_tasks: configure.yml
  tags:
    - configuration
    - rstudio-package-manager
    - rstudio-package-manager-configure

- name: Start and enable service
  ansible.builtin.service:
    name: rstudio-pm
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - rstudio-package-manager
    - rstudio-package-manager-start-enable-service

- name: Include repositories
  ansible.builtin.include_tasks: repositories.yml
  tags:
    - configuration
    - rstudio-package-manager
    - rstudio-package-manager-repositories
    - rstudio-package-manager-configure
    - molecule-notest
