# tasks file
---
- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - rstudio-package-manager
    - rstudio-package-manager-include-variables

- include: install.yml
  tags:
    - configuration
    - rstudio-package-manager
    - rstudio-package-manager-install
  notify: restart rstudio-package-manager

- include: configure.yml
  tags:
    - configuration
    - rstudio-package-manager
    - rstudio-package-manager-configure

- include: install-r.yml
  tags:
    - r-version-install

- name: start and enable service
  service:
    name: rstudio-pm
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - rstudio-package-manager
    - rstudio-package-manager-start-enable-service

- name: wait for port
  wait_for:
    port: "{{ rstudio_package_manager_www_port }}"
    delay: 60

- include: repositories.yml
  tags:
    - configuration
    - rstudio-package-manager
    - rstudio-package-manager-repositories
    - molecule-notest
