---

- name: Wait for server
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ rstudio_package_manager_www_port }}/__ping__"
    status_code:
      - 200
      - 402
  register: result
  until: result.status in [200, 402]
  retries: 60
  delay: 1

- name: Repositories | create CRAN repository
  ansible.builtin.shell: |
    /opt/rstudio-pm/bin/rspm create repo --name=cran --description='Access CRAN packages' || true
    /opt/rstudio-pm/bin/rspm subscribe --repo=cran --source=cran || true
    /opt/rstudio-pm/bin/rspm sync --type=cran
  changed_when: true
  when: rstudio_package_manager_enable_cran_repositories | bool
  tags:
    - rstudio-package-manager-repositories-cran

- name: Configure repositories
  tags:
    - rstudio-package-manager-repositories-ssh-key
  when:
    - rstudio_package_manager_ssh_key is defined
    - rstudio_package_manager_ssh_key|length
  block:
    - name: Repositories | write default SSH key to file
      ansible.builtin.copy:
        content: "{{ rstudio_package_manager_ssh_key }}"
        dest: "/var/lib/rstudio-pm/default-ssh-key"
        owner: root
        group: root
        mode: 0644

    - name: Repositories | import default SSH key
      ansible.builtin.shell: |
        /opt/rstudio-pm/bin/rspm import ssh-key --name=default --path=/var/lib/rstudio-pm/default-ssh-key || true
      register: out
      changed_when: out.rc != 0

- name: Repositories | create internal Git source and repository
  ansible.builtin.shell: |
    /opt/rstudio-pm/bin/rspm create source --type=git --name=internal-git-src || true
    /opt/rstudio-pm/bin/rspm create repo --name=internal-git --description='Stable releases of our internal packages' || true
    /opt/rstudio-pm/bin/rspm subscribe --source=internal-git-src --repo=internal-git || true
  when: rstudio_package_manager_enable_git_repositories | bool
  tags:
    - rstudio-package-manager-repositories-git

- name: Repositories | create Git builders
  ansible.builtin.shell: |
    /opt/rstudio-pm/bin/rspm create git-builder --source=internal-git-src --url={{ item.name }} --credential=default --build-trigger={{ item.trigger }} || true
  loop: "{{ rstudio_package_manager_git_repositories }}"
  when:
    - rstudio_package_manager_git_repositories is defined
    - rstudio_package_manager_git_repositories|length
  tags:
    - rstudio-package-manager-repositories-git
