---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../../tests/tasks/post.yml"
    - name: Include tasks
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../../tests/tasks/verify-run-as.yml"
      vars:
        run_as_user: "rstudio-pm"
        runs_as_group: "rstudio-pm"
