# tasks file
---
- name: Install | download deb
  ansible.builtin.get_url:
    url: "{{ rstudio_package_manager_download_url }}"
    dest: "{{ rstudio_package_manager_downloads_path }}/rstudio-package-manager-{{ rstudio_package_manager_version }}-{{ rstudio_package_manager_machine_map[ansible_machine] }}.deb"
    mode: '0755'
  tags:
    - rstudio-package-manager-install-download
    - rstudio-package-manager-install-download-deb

- name: Install | install deb
  ansible.builtin.apt:
    deb: "{{ rstudio_package_manager_downloads_path }}/rstudio-package-manager-{{ rstudio_package_manager_version }}-{{ rstudio_package_manager_machine_map[ansible_machine] }}.deb"
  tags:
    - rstudio-package-manager-install-install
    - rstudio-package-manager-install-install-deb
