# tasks file
---
- name: Install | download rpm
  ansible.builtin.get_url:
    url: "{{ rstudio_package_manager_download_url }}"
    dest: "{{ rstudio_package_manager_downloads_path }}/rstudio-package-manager-{{ rstudio_package_manager_version }}.rpm"
    mode: '0755'
  tags:
    - rstudio-package-manager-install-download
    - rstudio-package-manager-install-download-rpm

- name: Install | install rpm
  ansible.builtin.dnf:
    name: "{{ rstudio_package_manager_downloads_path }}/rstudio-package-manager-{{ rstudio_package_manager_version }}.rpm"
    disable_gpg_check: true
  tags:
    - rstudio-package-manager-install-install
    - rstudio-package-manager-install-install-rpm
