---
- name: Converge
  hosts: all
  become: true
  debugger: on_failed
  pre_tasks:
    - name: Include vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
    - name: Include vars for older version
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../tests/vars/older-version.yml"
  roles:
    - ../../../
